### ISSUE TITLE
Release 1.1.0 

### ISSUE THREAD

**Issue by Insuuu24** [IERO-6/DRBS-HomeComing#110]
### LaunchScreen
- [x] 런치스크린 이미지 추가
---
### LoginVC
- [ ] 애플 로그인이 영어로 되어있는 것을 한글로
- [x] 앱 버전 SettingVC 에서 이용한 로직 똑같이 적용하기 -> @Insuuu24
---
### SettingVC
- [x] 공지사항 좀 더 다양하게 변경 (파이어베이스 연동) -> @ryuwon2407
- [x] App Store 리뷰하기 스터디윗미 -> 도라방스로 변경 (추후에 리뷰까지 열리는 구조로 변경예정)
---
### HomeVC
- [x] 테이블뷰 제일 하단 스크롤 되었을때 탭바 백그라운드 색상, 탭바 상단 line 없어지는 현상 -> @kes3035
---
### DetailVC -> @Insuuu24
- [x] 추가된 체크리스트가 없을때 + 버튼 눌러서 CheckVC1 이동했다가 돌아오면 네비게이션 타이틀 없어지는 현상
- [x] NoDataView 비율 조정
---
### MyHouseVC
- [x] 편집시 북마크 해제되는 현상 해결
- [x] 관리비 미포함 다 체크해도 관리비 미포함 목록에 전부 반영안됨 -> @Enoun
- [x] 기타 이미지 만들고 추가하기
---
### CheckVC -> @ryuwon2407
- [ ] 카메라 아이콘 변경

**Comment by ryuwon-dev** [comment]
1.1.0에 추가로 checkVC에 카메라 아이콘을 변경했으면 합니다!

**Comment by ryuwon-dev** [comment]
LoginVC
애플 로그인이 영어로 되어있는 것을 한글로 바꾸는 작업도 필요할것같아요

**Comment by kes3035** [comment]
MyHouseVC에서 관리비 미포함 목록에 기타를 선택해도 기타는 이미지가 따로 없어서 추가해야할 것 같네요
