### ISSUE TITLE
CheckVC1, CheckVC2 텍스트필드 입력 값

### ISSUE THREAD

**Issue by kes3035** [IERO-6/DRBS-HomeComing#26]
|CheckVC1|CheckVC2|
|---|---| 
|- 이름TextField : 최대 글자 수 지정|- 각 텍스트필드 숫자만 입력할 수 있도록, 너무 많은 금액은 입력할 수 없게 글자수 제한도|
||사진권한, 체크리스트 커스텀UIView로 만들기, galleryImageView 호라이즌 스크롤뷰 max 5, UIView 레이아웃|

**Dealine -> 08.25**

버튼 이슈는 제가 해결해보겠슴다!! 코드가 넘 깔끔해졌어요!!!!!!🥰

**Comment by Insuuu24** [comment]
* CheckVC1 -> nameTextField 글자수 10개로 제한 구현 완료.
