### ISSUE TITLE
CheckVC1 기능 요구

### ISSUE THREAD

**Issue by kes3035** [IERO-6/DRBS-HomeComing#31]
CheckVC1 들어오면 바로 nameTextField 입력할 수 있게 키보드 올라오는 로직
nameTextField 에 입력되는 글자수 최대 10자..?로 제한, 리턴키 누르면 키보드 내려가게

addressTextField 누르면 키보드 올라오면서 레이아웃 잡아주는 로직

+++현재 textFieldShouldReturn 에 addressTextField 분기 처리를 진행하지 않았으니 nameTextField 리턴키 눌렀을 때 키보드 내려가는 로직은
`if textField == nameTextField {**여기에 구현**} `

**Comment by Insuuu24** [comment]
1. CheckVC1 들어오면 바로 nameTextField 입력할 수 있게 키보드 올라오는 기능 구현

2. nameTextField 에 입력되는 글자수 최대 10자로 제한, 리턴키 누르면 키보드 내려가는 기능 구현

3. addressTextField 누르면 키보드 올라오면서 레이아웃 잡아주는 로직

4. textFieldShouldReturn 에 addressTextField 분기 처리를 진행하지 않았으니 nameTextField 리턴키 눌렀을 때 키보드 내려가는 로직 구현

5. 네비게이션 바 재조정
