### ISSUE TITLE
현재 진행상황 전반적인 이슈.tar

### ISSUE THREAD

**Issue by kes3035** [IERO-6/DRBS-HomeComing#46]
## SettingVC
-  ~~SettingVC에서 HomeVC로 돌아왔을 때, HomeVC 네비게이션바 색상 안바뀌는 오류~~   => 해결
-  ~~SettingVC들어갈 때, tabbar 부분을 숨기는 과정에서 검정색 부분 보이는 오류~~ => 해결
- 메일 보내기 사용가능한지 테스트 불가 => 엘리엇 기기에서는 테스트 어려움 ㅠ (구석기 폰)
- ~~회원탈퇴시 사유 작성하는 textView 글자수 제한이 있는지 ?~~
- ~~로그아웃 로그인 구현아직 안돼서 로그아웃 테스트 불가~~

-----------
## HomeVC
- ~~cell마다 데이터를 받아와서 띄우는 작업~~
- ~~cell UI 완성된건지?~~
- ~~detailVC UI 완성된건지?~~
- ~~BookMark된 셀들 아래에 추가적으로 넣어야함~~

------------
## CheckVC1
- ~~keyBoard가 올라오는 것에 따라 화면 레이아웃 조정하는 코드에서 화면이 작은 엘리엇의 기기로 테스트해보니 키보드에 자동완성란 때문에 보이지 않는 이슈 해당 공간 고려하여 더 올려야 할 것 같음~~
------------
## CheckVC2
- ~~CheckVC1에서 전세버튼을 눌렀을 땐 전세* 로 표기해야함~~
- ~~**보증금, 월세, 관리비,면적, 계약기간 textField** 글자수 제한 + 숫자와 **특수문자**( ex 12.6만원) 입력 가능하도록~~
- ~~체크리스트 여러개 입력받아도 될지? (*현재는 여러개 입력도 가능하게 하고 있음 그러나 있음과 없음이 동시에 눌려도 될 것인지?*)~~
- ~~기록에서 앨범에 접근해서 사진을 추가할 때, 카메라 이미지뷰를 누르면 앨범 접근, 사진들을 누르면 사진을 크게 볼 수 있는 커스텀 팝업 뷰~~
- 커스텀 팝업 뷰까지 구현했으나 아직 이미지를 ImageUrl로 변환하거나 화면에 띄우는 로직은 존재 X
- ~~빈 화면 터치시 키보드가 내려가야함~~
- ~~메모 글자수 500자 제한~~
--------------
## RateVC
- UI 간격만 더 조정하면 될 듯
- 저장버튼을 눌렀을 때, 모델을 생성해서 서버에 올리는 코드 간결화 필요 ->  류원님 도움 **절 실**
-------------
## MapVC
- ~~커스텀 어노테이션 뷰 UI 이질감 줄이기~~
- ~~커스텀 어노테이션 뷰 터치시, 해당 부동산에 관한 정보 띄우는 DetailVC UI 필요 (HomeVC에서 detailVC 넘어가서 쓰는 UI와 동일)~~
- ~~최초 설치 후 앱 권한 설정 마친 후 내 위치 버튼 누르면 앱 종료되는 오류~~
- ~~재접속 후 내 위치 누를 시 줌레벨 오류~~

**Comment by Insuuu24** [comment]
### SettingVC
* 메일 보내기 사용가능한지 테스트 불가 => 엘리엇 기기에서는 테스트 어려움 ㅠ (구석기 폰)
-> 메일앱을 통해 메일을 연결해야 작동이 되는거라 추후 배포이전에 최종테스트 진행

* ~~회원탈퇴시 사유 작성하는 textView 글자수 제한이 있는지 ?~~
-> 50자 제한 (추가로 PlaceHolder까지 설정완료) 구현 완료

### CheckVC1
* ~~keyBoard가 올라오는 것에 따라 화면 레이아웃 조정하는 코드에서 화면이 작은 엘리엇의 기기로 테스트해보니 키보드에 자동완성란 때문에 보이지 않는 이슈 해당 공간 고려하여 더 올려야 할 것 같음~~
-> addressTextField 키보드 레이아웃 기기별 대응 구현 완료

**Comment by ryuwon-dev** [comment]
### LoginVC
- 이미 firebase Auth에 존재하는데 “notice: 이미 계정이 존재합니다.” 로직에 걸리지가 않음..
- 뷰 전환 코드 VC로 옮기기 ⇒  비동기 필요 (Combine 사용 예정)
- 현재 로그인 API 비동기 처리가 되어 있지 않아 로딩이 좀 걸리는 것처럼 느껴짐
    ⇒ 차후 로그인 API에 대한 네트워크 로직 비동기 처리 필요
